/**
 * EduTrend AI Agent — Content Export Utilities
 * Supports JSON, Markdown, and clipboard export.
 */

/**
 * Trigger a file download in the browser.
 */
function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export content as a JSON file.
 */
export function exportAsJSON(content) {
  const data = {
    ...content,
    exportedAt: new Date().toISOString(),
    exportVersion: "1.0",
  };
  const filename = `edutrend_${content.metadata?.niche?.replace(/\s+/g, "_") || "content"}_${Date.now()}.json`;
  downloadFile(JSON.stringify(data, null, 2), filename, "application/json");
}

/**
 * Export content as a Markdown file.
 */
export function exportAsMarkdown(content) {
  const seo = content.seo || {};
  const quality = content.quality || {};
  const meta = content.metadata || {};

  let md = `# ${seo.titles?.[0] || "Generated Content"}\n\n`;
  md += `> Generated by EduTrend AI Agent on ${new Date(meta.generatedAt || Date.now()).toLocaleString()}\n\n`;
  md += `**Niche:** ${meta.niche || "N/A"} | **Audience:** ${meta.audience || "N/A"} | **Platform:** ${meta.platform || "N/A"} | **Format:** ${meta.format?.replace(/_/g, " ") || "N/A"}\n\n`;
  md += `**Quality Score:** ${quality.score || "N/A"}/100 | **Est. Views:** ${quality.predictions?.views || "N/A"} | **Engagement:** ${quality.predictions?.engagementRate || "N/A"}\n\n`;
  md += `---\n\n`;

  // Script
  md += `## 📝 Script\n\n`;
  md += `${content.script || "No script generated."}\n\n`;
  md += `---\n\n`;

  // Title Variants
  if (seo.titles?.length) {
    md += `## 🏷️ Title Variants\n\n`;
    seo.titles.forEach((t, i) => {
      md += `${i + 1}. ${t}\n`;
    });
    md += `\n`;
  }

  // Description
  if (seo.description) {
    md += `## 📄 Description\n\n${seo.description}\n\n`;
  }

  // Instagram Captions
  if (seo.instagramCaptions?.length) {
    md += `## 📱 Instagram Captions\n\n`;
    seo.instagramCaptions.forEach((c, i) => {
      md += `### Variant ${String.fromCharCode(65 + i)}\n\n${c}\n\n`;
    });
  }

  // Hashtags
  if (seo.hashtags) {
    md += `## #️⃣ Hashtags\n\n`;
    if (seo.hashtags.mega?.length) md += `**Mega (>5M):** ${seo.hashtags.mega.join(" ")}\n\n`;
    if (seo.hashtags.mid?.length) md += `**Mid (500K-5M):** ${seo.hashtags.mid.join(" ")}\n\n`;
    if (seo.hashtags.niche?.length) md += `**Niche (<500K):** ${seo.hashtags.niche.join(" ")}\n\n`;
  }

  // Tags
  if (seo.tags?.length) {
    md += `## 🔖 YouTube Tags\n\n${seo.tags.join(", ")}\n\n`;
  }

  // Quality Suggestions
  if (quality.suggestions?.length) {
    md += `## 💡 Improvement Suggestions\n\n`;
    quality.suggestions.forEach((s) => {
      md += `- ${s}\n`;
    });
    md += `\n`;
  }

  md += `---\n*Pipeline: ${meta.pipeline || "Researcher → Writer → Editor → SEO Optimizer"}*\n`;

  const filename = `edutrend_${meta.niche?.replace(/\s+/g, "_") || "content"}_${Date.now()}.md`;
  downloadFile(md, filename, "text/markdown");
}

/**
 * Copy all content (script + SEO) to clipboard.
 */
export async function copyAllToClipboard(content) {
  const seo = content.seo || {};
  const allHashtags = [
    ...(seo.hashtags?.mega || []),
    ...(seo.hashtags?.mid || []),
    ...(seo.hashtags?.niche || []),
  ].join(" ");

  let text = "";
  text += `TITLE: ${seo.titles?.[0] || "N/A"}\n\n`;
  text += `SCRIPT:\n${content.script || ""}\n\n`;
  text += `DESCRIPTION:\n${seo.description || ""}\n\n`;
  text += `HASHTAGS:\n${allHashtags}\n\n`;
  if (seo.tags?.length) text += `TAGS:\n${seo.tags.join(", ")}\n`;

  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement("textarea");
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
    return true;
  }
}

/**
 * Copy just the SEO metadata to clipboard.
 */
export async function copySeoToClipboard(seo) {
  const allHashtags = [
    ...(seo.hashtags?.mega || []),
    ...(seo.hashtags?.mid || []),
    ...(seo.hashtags?.niche || []),
  ].join(" ");

  let text = "";
  if (seo.titles?.length) {
    text += `TITLES:\n`;
    seo.titles.forEach((t, i) => { text += `${i + 1}. ${t}\n`; });
    text += `\n`;
  }
  text += `DESCRIPTION:\n${seo.description || ""}\n\n`;
  if (seo.instagramCaptions?.length) {
    text += `INSTAGRAM CAPTIONS:\n`;
    seo.instagramCaptions.forEach((c, i) => {
      text += `Variant ${String.fromCharCode(65 + i)}:\n${c}\n\n`;
    });
  }
  text += `HASHTAGS:\n${allHashtags}\n\n`;
  if (seo.tags?.length) text += `TAGS:\n${seo.tags.join(", ")}\n`;

  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

/**
 * Export as plain text (simplified).
 */
export function exportAsText(content) {
  let text = `${content.seo?.titles?.[0] || "Generated Content"}\n`;
  text += `${"=".repeat(50)}\n\n`;
  text += `${content.script || ""}\n\n`;
  text += `${"=".repeat(50)}\n`;
  text += `Description: ${content.seo?.description || ""}\n`;

  const filename = `edutrend_${content.metadata?.niche?.replace(/\s+/g, "_") || "content"}_${Date.now()}.txt`;
  downloadFile(text, filename, "text/plain");
}
