/**
 * Skilizee — Content Calendar Store
 *
 * Durable, per-account persistence for the generated content calendar.
 *
 * Mirrors the storage strategy used by `lib/meta/scheduler.js`: Firestore when
 * credentials are configured, in-memory otherwise. A module-level object alone
 * is not enough — API routes run on serverless instances that are recycled
 * between requests, so a calendar generated by POST /api/meta/calendar would
 * vanish before the next GET could read it.
 */

const CALENDAR_COLLECTION = "content_calendars";

// In-memory fallback (also serves as a same-instance cache)
let memoryCalendars = {};

let firestoreDb = null;
async function getFirestore() {
  if (firestoreDb) return firestoreDb;
  try {
    const { getApps, getApp, initializeApp, cert } = await import("firebase-admin/app");
    const { getFirestore: getFs } = await import("firebase-admin/firestore");

    const projectId = process.env.FIREBASE_PROJECT_ID;
    const clientEmail = process.env.FIREBASE_CLIENT_EMAIL;
    const privateKey = process.env.FIREBASE_PRIVATE_KEY;

    if (!projectId || !clientEmail || !privateKey) return null;

    const apps = getApps();
    const app = apps.length > 0 ? getApp() : initializeApp({
      credential: cert({
        projectId,
        clientEmail,
        privateKey: privateKey.replace(/\\n/g, "\n"),
      }),
    });

    firestoreDb = getFs(app);
    return firestoreDb;
  } catch {
    return null;
  }
}

/** Firestore rejects `undefined`; a JSON round-trip drops those keys. */
function sanitize(value) {
  return JSON.parse(JSON.stringify(value));
}

/**
 * Persist the calendar for one account, replacing any previous one.
 * @param {object} calendar — normalized calendar from the calendar agent
 * @param {string} accountId
 * @param {object} [requestOptions] — the options the calendar was generated with
 * @returns {Promise<object>} — the stored record
 */
export async function saveCalendar(calendar, accountId = "skillizee", requestOptions = null) {
  if (!calendar) throw new Error("Calendar is required");

  const record = sanitize({
    ...calendar,
    accountId,
    cachedAt: new Date().toISOString(),
    requestOptions: requestOptions || null,
  });

  memoryCalendars[accountId] = record;

  const db = await getFirestore();
  if (db) {
    try {
      await db.collection(CALENDAR_COLLECTION).doc(accountId).set(record);
      console.log(`[Calendar Store] [${accountId}] Calendar persisted to Firestore.`);
      return record;
    } catch (err) {
      console.error("[Calendar Store] Firestore write failed:", err.message);
    }
  }

  console.log(`[Calendar Store] [${accountId}] Calendar held in memory.`);
  return record;
}

/**
 * Load the most recently generated calendar for one account.
 * @param {string} accountId
 * @returns {Promise<object|null>}
 */
export async function loadCalendar(accountId = "skillizee") {
  const db = await getFirestore();
  if (db) {
    try {
      const doc = await db.collection(CALENDAR_COLLECTION).doc(accountId).get();
      if (doc.exists) {
        const data = doc.data();
        memoryCalendars[accountId] = data;
        return data;
      }
      return memoryCalendars[accountId] || null;
    } catch (err) {
      console.error("[Calendar Store] Firestore read failed:", err.message);
    }
  }

  return memoryCalendars[accountId] || null;
}
